# QA Environment URLs and Credentials
SWITCH.URL=https://admin-swt.testtoucanpay.in/#/
login.api.url=https://admin-swt.testtoucanpay.in/api/uam/auth/login
api.username=admin
api.password=admin123
update.scheme.api.url=https://admin-swt.testtoucanpay.in/api/v1/admin/schemeDestination/upd