# QA Environment URLs and Credentials
SWITCH.URL=https://admin-swt.testtoucanpay.in/#/
#api.base.url=https://reqres.in/api
login.api.url=https://uam-dev.toucanint.com/api/uam/auth/login
api.username=admin
api.password=admin123
