extent.reporter.spark.start=true
extent.reporter.spark.out=Reporting/SparkReport.html

# Extent Cucumber Adapter Screenshots
screenshot.directory=Reporting/Screenshots/
screenshot.relativetopath=true

# Optional: Add system info to the report
systeminfo.os=Windows
systeminfo.user=FrameworkUser
